// Code generated by goctl. DO NOT EDIT.
package types

type AddReq struct {
	Plu         string `json:"plu"`
	Sku         string `json:"sku"`
	Name        string `json:"name"`
	Image       string `json:"image"`
	Description string `json:"description"`
	InStocked   string `json:"in_stocked"`
}

type AddReply struct {
	Id          int64  `json:"id"`
	Plu         string `json:"plu"`
	Sku         string `json:"sku"`
	Name        string `json:"name"`
	Image       string `json:"image"`
	Description string `json:"description"`
	InStocked   string `json:"in_stocked"`
}

type GetInfoReq struct {
	Id int64 `json:"id"`
}

type GetInfoReply struct {
	Id          int64  `json:"id"`
	Plu         string `json:"plu"`
	Sku         string `json:"sku"`
	Name        string `json:"name"`
	Image       string `json:"image"`
	Description string `json:"description"`
	InStocked   string `json:"in_stocked"`
}

type UpdateReq struct {
	Id          int64  `json:"id"`
	Plu         string `json:"plu"`
	Sku         string `json:"sku"`
	Name        string `json:"name"`
	Image       string `json:"image"`
	Description string `json:"description"`
	InStocked   string `json:"in_stocked"`
}

type UpdateReply struct {
	Id          int64  `json:"id"`
	Plu         string `json:"plu"`
	Sku         string `json:"sku"`
	Name        string `json:"name"`
	Image       string `json:"image"`
	Description string `json:"description"`
	InStocked   string `json:"in_stocked"`
}

type Book struct {
	Id          int64  `json:"id"`
	Plu         string `json:"plu"`
	Sku         string `json:"sku"`
	Name        string `json:"name"`
	Image       string `json:"image"`
	Description string `json:"description"`
	InStocked   string `json:"in_stocked"`
}

type SearchReq struct {
	Keyword string `json:"keyword"`
	Page string `json:"page"`
	PageSize string `json:"pagesize"`
	OrderBy string `json:"orderby"`
}

type SearchReply struct {
	Books   []*Book `json:"books"`
	IsEnd   bool    `json:"is_end"`
	LastVal int64   `json:"last_val"`
}
