// Code generated by goctl. DO NOT EDIT!
// Source: book.proto

package book

import (
	"context"

	"go-zero-bookmall/service/book/rpc/types/book"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	BookResponse = book.BookResponse
	IdRequest    = book.IdRequest

	Book interface {
		GetBook(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*BookResponse, error)
	}

	defaultBook struct {
		cli zrpc.Client
	}
)

func NewBook(cli zrpc.Client) Book {
	return &defaultBook{
		cli: cli,
	}
}

func (m *defaultBook) GetBook(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*BookResponse, error) {
	client := book.NewBookClient(m.cli.Conn())
	return client.GetBook(ctx, in, opts...)
}
