// Code generated by goctl. DO NOT EDIT!
// Source: book.proto

package server

import (
	"context"

	"go-zero-bookmall/service/book/rpc/internal/logic"
	"go-zero-bookmall/service/book/rpc/internal/svc"
	"go-zero-bookmall/service/book/rpc/types/book"
)

type BookServer struct {
	svcCtx *svc.ServiceContext
	book.UnimplementedBookServer
}

func NewBookServer(svcCtx *svc.ServiceContext) *BookServer {
	return &BookServer{
		svcCtx: svcCtx,
	}
}

func (s *BookServer) GetBook(ctx context.Context, in *book.IdRequest) (*book.BookResponse, error) {
	l := logic.NewGetBookLogic(ctx, s.svcCtx)
	return l.GetBook(in)
}
