// Code generated by goctl. DO NOT EDIT.
package types

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginReply struct {
	Id           int64  `json:"id"`
	Username         string `json:"username"`
	Email         string `json:"email"`
	Gender       string `json:"gender"`
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessexpire"`
	RefreshAfter int64  `json:"refreshAfter"`
}

type SignupReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Email         string `json:"email"`
	Gender   string `json:"gender"`
}

type SignupReply struct {
	Id           int64  `json:"id"`
	Username         string `json:"username"`
	Email         string `json:"email"`
	Gender       string `json:"gender"`
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessexpire"`
	RefreshAfter int64  `json:"refreshAfter"`
}

type GetProfileReq struct {
	Id int64 `json:"id"`
}

type GetProfileReply struct {
	Id     int64  `json:"id"`
	Username   string `json:"username"`
	Email   string `json:"email"`
	Gender string `json:"gender"`
}

type UpdateReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Email string `json:"email"`
	Gender   string `json:"gender"`
}

type UpdateReply struct {
	Id           int64  `json:"id"`
	Username         string `json:"username"`
	Email         string `json:"email"`
	Gender       string `json:"gender"`
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessexpire"`
	RefreshAfter int64  `json:"refreshAfter"`
}
